source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'AlternativeButton', :exclusive => true do
  pod "AlternativeButton", :path => "../"
  pod 'Reveal-iOS-SDK', '~> 1.5.1', :configurations => ['Debug']
end

target 'Tests', :exclusive => true do
  pod "AlternativeButton", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
